#!/bin/bash

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Building Node app ..."
COMMAND=$(cat <<EOF
cd "/app" &&
new_path="\$(find / -name npm | tail -1 | xargs -I % sh -c "dirname %")" &&
PATH="\$PATH:\$new_path" &&
PATH="\$PATH:\$(npm bin)" &&
gulp -v | grep Local || npm install -g gulp &&
gulp -v | grep CLI || npm install -g gulp-cli &&
npm install -g bower &&
bower --allow-root install &&
gulp build
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Built Node"
